language: go

go:
  - 1.9
  - "1.10"
  - 1.11
  - tip

services:
  - redis-server
  
before_install:
  - go get "gopkg.in/redis.v3"
  - go get github.com/axw/gocov/gocov
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
    - go test -v -covermode=count -coverprofile=coverage.out ./...
    - goveralls -coverprofile=coverage.out -service travis-ci -repotoken GybrsAp4vyE2dcHAUF7sBfpKGlVNQh0Jr